In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

pd.set_option('display.max_columns', None)

In [2]:
# MASTER TABLES
customer = pd.read_csv('improved_dim_customer.csv')
product = pd.read_csv("improved_dim_product.csv")
warehouse = pd.read_csv("improved_dim_warehouse.csv")
supplier = pd.read_csv("raw_dim_supplier.csv")

# FACT TABLES
purchase = pd.read_csv("raw_fact_purchase.csv")
inventory = pd.read_csv("raw_fact_inventory.csv")
sales = pd.read_csv("raw_fact_sales.csv")
shipment = pd.read_csv("raw_fact_shipment.csv")

In [3]:
def audit(df, name):
    print(f"\n{name} shape:", df.shape)
    print(df.isnull().sum())
    print(df.dtypes)

In [4]:
audit(product,"product")
print("------------------------------------------------------------------------------------------------------------------------")
audit(warehouse,"warehouse")
print("------------------------------------------------------------------------------------------------------------------------")
audit(supplier,"supplier")
print("------------------------------------------------------------------------------------------------------------------------")
audit(purchase,"purchase")
print("------------------------------------------------------------------------------------------------------------------------")
audit(inventory,"inventory")
print("------------------------------------------------------------------------------------------------------------------------")
audit(sales,"sales")
print("------------------------------------------------------------------------------------------------------------------------")
audit(shipment,"shipment")

product shape: (300, 12)
Product_ID         0
SKU_Code           0
Product_Name       0
Category           0
Sub_Category       0
Unit_Cost          0
Selling_Price      0
Weight_kg          0
Volume_m3          0
Shelf_Life_Days    0
Reorder_Level      0
Product_Status     0
dtype: int64
Product_ID          object
SKU_Code            object
Product_Name        object
Category            object
Sub_Category        object
Unit_Cost            int64
Selling_Price      float64
Weight_kg          float64
Volume_m3          float64
Shelf_Life_Days      int64
Reorder_Level        int64
Product_Status      object
dtype: object
------------------------------------------------------------------------------------------------------------------------

warehouse shape: (15, 8)
Warehouse_ID      0
Warehouse_Name    0
Country           0
State             0
City              0
Warehouse_Type    0
Capacity          0
Manager_Name      0
dtype: int64
Warehouse_ID      object
Warehouse_Name    object
Country           object
State             object
City              object
Warehouse_Type    object
Capacity           int64
Manager_Name      object
dtype: object
------------------------------------------------------------------------------------------------------------------------

supplier shape: (200, 7)
Supplier_ID        0
Supplier_Name      0
Supplier_Type      0
Country            0
Lead_Time_Days     0
Contract_Type      0
Supplier_Rating    5
dtype: int64
Supplier_ID         object
Supplier_Name       object
Supplier_Type       object
Country             object
Lead_Time_Days       int64
Contract_Type       object
Supplier_Rating    float64
dtype: object
------------------------------------------------------------------------------------------------------------------------

purchase shape: (10000, 10)
PO_ID                     0
Supplier_ID               0
Product_ID                0
Order_Date                0
Expected_Delivery_Date    0
Actual_Delivery_Date      0
Quantity_Ordered          0
Quantity_Received         0
Unit_Cost                 0
PO_Status                 0
dtype: int64
PO_ID                     object
Supplier_ID               object
Product_ID                object
Order_Date                object
Expected_Delivery_Date    object
Actual_Delivery_Date      object
Quantity_Ordered           int64
Quantity_Received          int64
Unit_Cost                  int64
PO_Status                 object
dtype: object
------------------------------------------------------------------------------------------------------------------------

inventory shape: (10000, 9)
Inventory_ID        0
Warehouse_ID        0
Product_ID          0
Inventory_Date      0
Opening_Stock       0
Inbound_Qty         0
Outbound_Qty        0
Closing_Stock     486
Storage_Cost        0
dtype: int64
Inventory_ID       object
Warehouse_ID       object
Product_ID         object
Inventory_Date     object
Opening_Stock       int64
Inbound_Qty         int64
Outbound_Qty        int64
Closing_Stock     float64
Storage_Cost      float64
dtype: object
------------------------------------------------------------------------------------------------------------------------

sales shape: (10000, 8)
Sales_Order_ID      0
Customer_ID         0
Product_ID          0
Order_Date          0
Quantity_Ordered    0
Order_Value         0
Order_Channel       0
Order_Status        0
dtype: int64
Sales_Order_ID      object
Customer_ID         object
Product_ID          object
Order_Date          object
Quantity_Ordered     int64
Order_Value          int64
Order_Channel       object
Order_Status        object
dtype: object
------------------------------------------------------------------------------------------------------------------------

shipment shape: (10000, 13)
Shipment_ID              0
Sales_Order_ID           0
Warehouse_ID             0
Transport_Mode           0
Dispatch_Date            0
Delivery_Date            0
SLA_Days                 0
Actual_Days            186
Delivery_Status          0
Distance_KM              0
Total_Shipping_Cost      0
Revenue                  0
Profit                   0
dtype: int64
Shipment_ID             object
Sales_Order_ID          object
Warehouse_ID            object
Transport_Mode          object
Dispatch_Date           object
Delivery_Date           object
SLA_Days                 int64
Actual_Days            float64
Delivery_Status         object
Distance_KM              int64
Total_Shipping_Cost    float64
Revenue                  int64
Profit                 float64
dtype: object

In [61]:
customer['Customer_Type']= customer['Customer_Type'].str.upper()

In [71]:
customer

,Customer_ID,Customer_Name,Customer_Type,Industry,Region,Contract_Type,Credit_Terms
0,CUST_0001,Arjun Logistics,B2B,Healthcare,APAC,Annual,Net30
1,CUST_0002,Arjun Distributors,B2B,Ecommerce,APAC,Annual,Net30
2,CUST_0003,Krishna Solutions,B2B,Automotive,North America,Annual,Net60
3,CUST_0004,Ishaan Retail,B2B,Healthcare,APAC,Annual,Net60
4,CUST_0005,Rohan Corporation,B2B,Retail,Europe,Annual,Net30
...,...,...,...,...,...,...,...
495,CUST_0496,Karan Logistics,B2B,Healthcare,North America,Annual,Net30
496,CUST_0497,Sneha Enterprises,B2C,Automotive,APAC,Quarterly,Net60
497,CUST_0498,Vihaan Industries,B2B,Healthcare,Europe,Annual,Net60
498,CUST_0499,Krishna Solutions,B2B,Automotive,Europe,Quarterly,Net30
499,CUST_0500,Aarav Logistics,B2C,Ecommerce,North America,Quarterly,Net30

# Clean Product Table

In [5]:
product['Category']= product['Category'].str.title()

In [6]:
product

,Product_ID,SKU_Code,Product_Name,Category,Sub_Category,Unit_Cost,Selling_Price,Weight_kg,Volume_m3,Shelf_Life_Days,Reorder_Level,Product_Status
0,PROD_0001,SKU-1001,Business Laptop Model-375,Electronics,Premium,184,244.57,4.63,0.142,139,143,Active
1,PROD_0002,SKU-1002,Smart Barcode Scanner Model-874,Electronics,Premium,463,666.49,14.29,0.170,357,314,Active
2,PROD_0003,SKU-1003,Safety Helmet Model-586,Electronics,Premium,401,622.92,12.43,0.025,107,357,Active
3,PROD_0004,SKU-1004,Electric Actuator Model-793,Electronics,Premium,314,480.47,3.89,0.154,178,185,Active
4,PROD_0005,SKU-1005,Warehouse Rack Model-143,Pharma,Premium,463,609.98,24.72,0.093,165,404,Active
...,...,...,...,...,...,...,...,...,...,...,...,...
295,PROD_0296,SKU-1296,Conveyor Motor Model-921,Electronics,Standard,221,297.16,16.70,0.084,213,475,Active
296,PROD_0297,SKU-1297,Electric Actuator Model-445,Automotive,Standard,444,585.29,14.14,0.138,124,106,Active
297,PROD_0298,SKU-1298,Packaging Tape Roll Model-801,Pharma,Standard,100,143.38,6.27,0.064,188,117,Active
298,PROD_0299,SKU-1299,Industrial Router Model-708,Automotive,Economy,367,470.56,16.31,0.145,151,144,Active
299,PROD_0300,SKU-1300,Electric Actuator Model-882,Electronics,Premium,116,160.26,22.50,0.142,219,250,Active

# Loss-making row removedabs
# Only valid pricing retained

In [7]:
product=product[product['Selling_Price']>=product['Unit_Cost']]

In [8]:
product

,Product_ID,SKU_Code,Product_Name,Category,Sub_Category,Unit_Cost,Selling_Price,Weight_kg,Volume_m3,Shelf_Life_Days,Reorder_Level,Product_Status
0,PROD_0001,SKU-1001,Business Laptop Model-375,Electronics,Premium,184,244.57,4.63,0.142,139,143,Active
1,PROD_0002,SKU-1002,Smart Barcode Scanner Model-874,Electronics,Premium,463,666.49,14.29,0.170,357,314,Active
2,PROD_0003,SKU-1003,Safety Helmet Model-586,Electronics,Premium,401,622.92,12.43,0.025,107,357,Active
3,PROD_0004,SKU-1004,Electric Actuator Model-793,Electronics,Premium,314,480.47,3.89,0.154,178,185,Active
4,PROD_0005,SKU-1005,Warehouse Rack Model-143,Pharma,Premium,463,609.98,24.72,0.093,165,404,Active
...,...,...,...,...,...,...,...,...,...,...,...,...
295,PROD_0296,SKU-1296,Conveyor Motor Model-921,Electronics,Standard,221,297.16,16.70,0.084,213,475,Active
296,PROD_0297,SKU-1297,Electric Actuator Model-445,Automotive,Standard,444,585.29,14.14,0.138,124,106,Active
297,PROD_0298,SKU-1298,Packaging Tape Roll Model-801,Pharma,Standard,100,143.38,6.27,0.064,188,117,Active
298,PROD_0299,SKU-1299,Industrial Router Model-708,Automotive,Economy,367,470.56,16.31,0.145,151,144,Active
299,PROD_0300,SKU-1300,Electric Actuator Model-882,Electronics,Premium,116,160.26,22.50,0.142,219,250,Active

# Clean Warehouse Table

In [9]:
warehouse['Country']=warehouse['Country'].str.title()

# Clean Supplier Table

In [10]:
supplier['Supplier_Type'] = supplier['Supplier_Type'].str.title()

In [11]:
supplier['Supplier_Rating'] = supplier['Supplier_Rating'].fillna(
    supplier['Supplier_Rating'].median()
)

In [12]:
supplier.isnull().sum()

Supplier_ID        0
Supplier_Name      0
Supplier_Type      0
Country            0
Lead_Time_Days     0
Contract_Type      0
Supplier_Rating    0
dtype: int64

# Clean FACT TABLES

In [13]:
purchase['Order_Date'] = pd.to_datetime(
    purchase['Order_Date'],
    errors='coerce',
    dayfirst=True
)

purchase['Expected_Delivery_Date'] = pd.to_datetime(
    purchase['Expected_Delivery_Date']
)

purchase['Actual_Delivery_Date'] = pd.to_datetime(
    purchase['Actual_Delivery_Date']
)

In [14]:
purchase['Order_Date'] = (
    purchase['Order_Date']
    .astype(str)
    .str.strip()
)

In [15]:
purchase['Order_Date'] = pd.to_datetime(
    purchase['Order_Date'],
    errors='coerce',
    dayfirst=True
)

In [16]:
purchase['Order_Date'] = pd.to_datetime(
    purchase['Order_Date'],
    errors='coerce',
    infer_datetime_format=True,
    dayfirst=True
)

In [17]:
purchase['Order_Date'] = purchase['Order_Date'].fillna(
    purchase['Expected_Delivery_Date'] - pd.Timedelta(days=7)
)

In [18]:
purchase['Order_Date'].isna().mean() * 100

0.0

In [19]:
purchase.loc[purchase['Order_Date'].isna(), 'Order_Date'].head(20)

Series([], Name: Order_Date, dtype: datetime64[ns])

In [20]:
purchase['Order_Date'].value_counts().head(20)

Order_Date
2024-07-25    41
2024-06-09    41
2024-04-17    41
2024-05-03    41
2024-12-24    40
2024-09-16    40
2024-02-08    39
2024-06-01    39
2024-07-19    39
2024-12-25    39
2024-12-17    38
2024-03-12    38
2024-05-07    38
2024-08-25    38
2024-04-24    37
2024-08-13    37
2024-01-24    37
2024-10-22    37
2024-10-12    37
2024-01-28    36
Name: count, dtype: int64

In [21]:
purchase['Order_Date'].sample(20)

7661   2024-10-06
7265   2024-01-27
9970   2024-08-27
3824   2024-03-31
9347   2024-02-04
4736   2024-03-06
8945   2024-08-02
9662   2024-03-18
6231   2024-07-03
3491   2024-04-09
9386   2024-04-08
8283   2024-12-24
5440   2024-01-27
780    2024-04-03
629    2024-08-06
5541   2024-11-15
3114   2024-03-05
390    2024-08-25
2879   2024-01-01
5917   2024-05-02
Name: Order_Date, dtype: datetime64[ns]

In [22]:
purchase['Order_Date'] = (
    purchase['Order_Date']
    .astype(str)
    .str.strip()
    .replace(['', 'nan', 'None', 'NaT'], np.nan)
)

In [23]:
parsed_date = pd.to_datetime(
    purchase['Order_Date'],
    errors='coerce',
    dayfirst=True
)

In [24]:
mask = parsed_date.isna()

parsed_date.loc[mask] = pd.to_datetime(
    purchase.loc[mask, 'Order_Date'],
    errors='coerce',
    dayfirst=False
)

In [25]:
purchase['Order_Date'] = parsed_date

In [26]:
purchase['Order_Date'].isna().mean() * 100

0.0

In [27]:
purchase.dtypes

PO_ID                             object
Supplier_ID                       object
Product_ID                        object
Order_Date                datetime64[ns]
Expected_Delivery_Date    datetime64[ns]
Actual_Delivery_Date      datetime64[ns]
Quantity_Ordered                   int64
Quantity_Received                  int64
Unit_Cost                          int64
PO_Status                         object
dtype: object

# Clean Inventory Table

In [28]:
inventory.dtypes

Inventory_ID       object
Warehouse_ID       object
Product_ID         object
Inventory_Date     object
Opening_Stock       int64
Inbound_Qty         int64
Outbound_Qty        int64
Closing_Stock     float64
Storage_Cost      float64
dtype: object

In [29]:
inventory['Inventory_Date'] = pd.to_datetime(
    inventory['Inventory_Date'],
    dayfirst=True
)

In [30]:
inventory.isna().sum()

Inventory_ID        0
Warehouse_ID        0
Product_ID          0
Inventory_Date      0
Opening_Stock       0
Inbound_Qty         0
Outbound_Qty        0
Closing_Stock     486
Storage_Cost        0
dtype: int64

In [31]:
inventory['Closing_Stock'] = inventory['Closing_Stock'].fillna(
    inventory['Opening_Stock']
    + inventory['Inbound_Qty']
    - inventory['Outbound_Qty']
)

In [32]:
inventory.isna().sum()

Inventory_ID      0
Warehouse_ID      0
Product_ID        0
Inventory_Date    0
Opening_Stock     0
Inbound_Qty       0
Outbound_Qty      0
Closing_Stock     0
Storage_Cost      0
dtype: int64

# Clean Shipment Table

In [33]:
shipment['Dispatch_Date'] = pd.to_datetime(
    shipment['Dispatch_Date'],
    dayfirst=True
)

shipment['Delivery_Date'] = pd.to_datetime(
    shipment['Delivery_Date']
)

In [34]:
shipment.isna().sum()

Shipment_ID              0
Sales_Order_ID           0
Warehouse_ID             0
Transport_Mode           0
Dispatch_Date            0
Delivery_Date            0
SLA_Days                 0
Actual_Days            186
Delivery_Status          0
Distance_KM              0
Total_Shipping_Cost      0
Revenue                  0
Profit                   0
dtype: int64

In [35]:
shipment['Actual_Days'] = shipment['Actual_Days'].fillna(
shipment['SLA_Days']
)

In [36]:
# Fix negative shipping cost
shipment.loc[
    shipment['Total_Shipping_Cost'] < 0,
    'Total_Shipping_Cost'
] = abs(shipment['Total_Shipping_Cost'])

In [37]:
# Recalculate Profit
shipment['Profit'] = (
    shipment['Revenue'] -shipment['Total_Shipping_Cost']
)

In [38]:
shipment

,Shipment_ID,Sales_Order_ID,Warehouse_ID,Transport_Mode,Dispatch_Date,Delivery_Date,SLA_Days,Actual_Days,Delivery_Status,Distance_KM,Total_Shipping_Cost,Revenue,Profit
0,SHP_100000,SO_104843,WH_04,Sea,2024-04-14,2024-04-24,3,10.0,Delayed,4909,2688.65,11976,9287.35
1,SHP_100001,SO_109704,WH_12,Road,2024-02-11,2024-02-14,3,3.0,On Time,1596,13121.40,37598,24476.60
2,SHP_100002,SO_107698,WH_10,Air,2024-05-01,2024-05-03,7,2.0,On Time,3519,6820.97,17925,11104.03
3,SHP_100003,SO_109809,WH_08,Sea,2024-09-17,2024-09-27,6,10.0,Delayed,3254,7989.27,20340,12350.73
4,SHP_100004,SO_104503,WH_03,Road,2024-04-03,2024-04-06,3,3.0,On Time,443,6675.38,29317,22641.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,SHP_109995,SO_100471,WH_09,Rail,2024-03-05,2024-03-15,6,10.0,Delayed,3934,11973.67,43512,31538.33
9996,SHP_109996,SO_104539,WH_14,Rail,2024-05-11,2024-05-20,4,9.0,Delayed,3153,5154.35,19891,14736.65
9997,SHP_109997,SO_102405,WH_03,Rail,2024-04-25,2024-04-30,3,5.0,Delayed,3290,4168.08,13398,9229.92
9998,SHP_109998,SO_101389,WH_11,Sea,2024-12-02,2024-12-08,7,6.0,On Time,3870,14574.81,38628,24053.19
9999,SHP_109999,SO_107241,WH_11,Road,2024-03-08,2024-03-14,4,6.0,Delayed,3415,1180.97,5577,4396.03

# 1. Transit Time
actual shipment duration.

In [39]:
shipment["Transit_Time"] = (
    shipment['Delivery_Date']-shipment['Dispatch_Date']
)

# 2. Delay Days
How many days the shipment/order is late

In [40]:
shipment['Delay_Days']=(
    shipment['Actual_Days']-shipment['SLA_Days']
)

# 3.Delay Flag
Whether it is late or not (binary indicator)
0 ---> on time 
1 ---> Delayed

In [41]:
shipment['Delay_Flag'] = (
    shipment['Actual_Days'].fillna(0) >
    shipment['SLA_Days'].fillna(0)
).astype(int)

# 4.Cost per KM

In [42]:
shipment['Cost_per_KM'] = (
   round( shipment['Total_Shipping_Cost']/shipment['Distance_KM'] ,2)
)

In [43]:
shipment

,Shipment_ID,Sales_Order_ID,Warehouse_ID,Transport_Mode,Dispatch_Date,Delivery_Date,SLA_Days,Actual_Days,Delivery_Status,Distance_KM,Total_Shipping_Cost,Revenue,Profit,Transit_Time,Delay_Days,Delay_Flag,Cost_per_KM
0,SHP_100000,SO_104843,WH_04,Sea,2024-04-14,2024-04-24,3,10.0,Delayed,4909,2688.65,11976,9287.35,10 days,7.0,1,0.55
1,SHP_100001,SO_109704,WH_12,Road,2024-02-11,2024-02-14,3,3.0,On Time,1596,13121.40,37598,24476.60,3 days,0.0,0,8.22
2,SHP_100002,SO_107698,WH_10,Air,2024-05-01,2024-05-03,7,2.0,On Time,3519,6820.97,17925,11104.03,2 days,-5.0,0,1.94
3,SHP_100003,SO_109809,WH_08,Sea,2024-09-17,2024-09-27,6,10.0,Delayed,3254,7989.27,20340,12350.73,10 days,4.0,1,2.46
4,SHP_100004,SO_104503,WH_03,Road,2024-04-03,2024-04-06,3,3.0,On Time,443,6675.38,29317,22641.62,3 days,0.0,0,15.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,SHP_109995,SO_100471,WH_09,Rail,2024-03-05,2024-03-15,6,10.0,Delayed,3934,11973.67,43512,31538.33,10 days,4.0,1,3.04
9996,SHP_109996,SO_104539,WH_14,Rail,2024-05-11,2024-05-20,4,9.0,Delayed,3153,5154.35,19891,14736.65,9 days,5.0,1,1.63
9997,SHP_109997,SO_102405,WH_03,Rail,2024-04-25,2024-04-30,3,5.0,Delayed,3290,4168.08,13398,9229.92,5 days,2.0,1,1.27
9998,SHP_109998,SO_101389,WH_11,Sea,2024-12-02,2024-12-08,7,6.0,On Time,3870,14574.81,38628,24053.19,6 days,-1.0,0,3.77
9999,SHP_109999,SO_107241,WH_11,Road,2024-03-08,2024-03-14,4,6.0,Delayed,3415,1180.97,5577,4396.03,6 days,2.0,1,0.35

# 5.Revenue per KM

In [44]:
shipment['Revenue_per_KM'] =(
   round( shipment['Revenue']/shipment['Distance_KM'])
)

# 6.. Profit Margin %

In [45]:
shipment['Profit_Margin_%'] = (
  round(  shipment['Profit'] / shipment['Revenue'] * 100)
)

# 7. Inventory Health Flag  
it is a binary business indicator that tells whether current inventory is in a healthy state based on predefined supply thresholds.
0 ---> healthy 
1 ----> unhealthy

In [46]:
inventory['Stock_Gap'] = (
    inventory['Closing_Stock']
    - (inventory['Opening_Stock']
       + inventory['Inbound_Qty']
       - inventory['Outbound_Qty'])
)

 This returns Boolean values:
 True --> mismatch exists
 False --> perfectly matched
 This converts:
 True --> 1
 False --> 0

In [47]:
inventory['Stock_Mismatch_Flag'] = (
    inventory['Stock_Gap'] != 0
).astype(int)

# 8.Purchase Lead Time
How many days it takes to receive goods after placing a purchase order.  OR It is the waiting time between ordering and receiving.

In [48]:
purchase['Lead_Time_Actual'] = (
    purchase['Actual_Delivery_Date']
    - purchase['Order_Date']
).dt.days

# 10.Shipment Cost Deviation %
How much the actual shipment cost is higher or lower than the planned (expected) cost

In [49]:
avg_cost_by_mode = shipment.groupby('Transport_Mode')['Total_Shipping_Cost'].transform('mean')

shipment['Cost_Deviation_%'] = (
    (shipment['Total_Shipping_Cost'] - avg_cost_by_mode)
    / avg_cost_by_mode * 100
)

# 11. Warehouse Load Utilization Proxy
An estimated indicator of how much warehouse capacity is being used.
Because many companies don’t have exact capacity data, they create a proxy (approximate measure).

In [50]:
inventory['Throughput'] = (
    inventory['Inbound_Qty'] + inventory['Outbound_Qty']
)

inventory['Warehouse_Load_Index'] = (
    inventory['Throughput'] /
    inventory.groupby('Warehouse_ID')['Throughput'].transform('mean')
)

# 12. Order Fulfillment Speed Bucket
A category that groups orders based on how fast they were fulfilled.

# Transit Time 
How many days a shipment takes to travel from dispatch to delivery.  or Shipment ko warehouse se customer tak pahunchne me kitna time laga?

In [52]:
# shipment.drop(columns=['Fulfillment_Speed'],axis=1,inplace=True)

In [53]:
shipment['Transit_Time']=(shipment['Delivery_Date']-shipment['Dispatch_Date'])

In [54]:
shipment['Transit_Time_Days'] = shipment['Transit_Time'].dt.days

In [55]:
shipment['Fulfillment_Speed'] = pd.cut(
    shipment['Transit_Time_Days'],
    bins=[0, 3, 6, 10, np.inf],
    labels=['Express Fast', 'Standard', 'Slow', 'Very Slow'],
    include_lowest=True
)

In [56]:
shipment

,Shipment_ID,Sales_Order_ID,Warehouse_ID,Transport_Mode,Dispatch_Date,Delivery_Date,SLA_Days,Actual_Days,Delivery_Status,Distance_KM,Total_Shipping_Cost,Revenue,Profit,Transit_Time,Delay_Days,Delay_Flag,Cost_per_KM,Revenue_per_KM,Profit_Margin_%,Cost_Deviation_%,Transit_Time_Days,Fulfillment_Speed
0,SHP_100000,SO_104843,WH_04,Sea,2024-04-14,2024-04-24,3,10.0,Delayed,4909,2688.65,11976,9287.35,10 days,7.0,1,0.55,2.0,78.0,-67.257027,10,Slow
1,SHP_100001,SO_109704,WH_12,Road,2024-02-11,2024-02-14,3,3.0,On Time,1596,13121.40,37598,24476.60,3 days,0.0,0,8.22,24.0,65.0,60.500795,3,Express Fast
2,SHP_100002,SO_107698,WH_10,Air,2024-05-01,2024-05-03,7,2.0,On Time,3519,6820.97,17925,11104.03,2 days,-5.0,0,1.94,5.0,62.0,-17.476647,2,Express Fast
3,SHP_100003,SO_109809,WH_08,Sea,2024-09-17,2024-09-27,6,10.0,Delayed,3254,7989.27,20340,12350.73,10 days,4.0,1,2.46,6.0,61.0,-2.704907,10,Slow
4,SHP_100004,SO_104503,WH_03,Road,2024-04-03,2024-04-06,3,3.0,On Time,443,6675.38,29317,22641.62,3 days,0.0,0,15.07,66.0,77.0,-18.346838,3,Express Fast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,SHP_109995,SO_100471,WH_09,Rail,2024-03-05,2024-03-15,6,10.0,Delayed,3934,11973.67,43512,31538.33,10 days,4.0,1,3.04,11.0,72.0,45.491975,10,Slow
9996,SHP_109996,SO_104539,WH_14,Rail,2024-05-11,2024-05-20,4,9.0,Delayed,3153,5154.35,19891,14736.65,9 days,5.0,1,1.63,6.0,74.0,-37.369531,9,Slow
9997,SHP_109997,SO_102405,WH_03,Rail,2024-04-25,2024-04-30,3,5.0,Delayed,3290,4168.08,13398,9229.92,5 days,2.0,1,1.27,4.0,69.0,-49.353691,5,Standard
9998,SHP_109998,SO_101389,WH_11,Sea,2024-12-02,2024-12-08,7,6.0,On Time,3870,14574.81,38628,24053.19,6 days,-1.0,0,3.77,10.0,62.0,77.495252,6,Standard
9999,SHP_109999,SO_107241,WH_11,Road,2024-03-08,2024-03-14,4,6.0,Delayed,3415,1180.97,5577,4396.03,6 days,2.0,1,0.35,2.0,79.0,-85.554390,6,Standard

# LOAD  DATA TABLES  IN TO MYSQL

In [68]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Supesh@localhost:3306/supply_chain_dw"
)

In [69]:
customer.to_sql("customer",engine,if_exists="replace",index=False)
product.to_sql( "product", engine, if_exists="replace", index=False)
warehouse.to_sql( "warehouse", engine, if_exists="replace", index=False)
supplier.to_sql( "supplier",engine,if_exists="replace",index=False)

200

In [70]:
purchase.to_sql("purchase",engine,if_exists="replace",index=False)
inventory.to_sql("inventory",engine,if_exists="replace",index=False)
sales.to_sql( "sales", engine, if_exists="replace", index=False)
shipment.to_sql("shipment", engine,if_exists="replace",index=False)

10000